<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_57109fa36957e',
	'title' => 'Widget: Text & Image Box',
	'fields' => array (
		array (
			'key' => 'field_57109fb700f16',
			'label' => 'Widget Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5710aef5fbd97',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5710b5175f0b1',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image_crop',
			'instructions' => 'Please crop image',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5710b8c3a2cf8',
						'operator' => '!=',
						'value' => 'none',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'crop_type' => 'hard',
			'target_size' => 'custom',
			'width' => 600,
			'height' => 320,
			'preview_size' => 'full',
			'force_crop' => 'yes',
			'save_in_media_library' => 'no',
			'retina_mode' => 'no',
			'save_format' => 'object',
			'library' => 'all',
		),
		array (
			'key' => 'field_574ebafb9e8d5',
			'label' => 'Advanced',
			'name' => 'advanced',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5710af23fbd98',
			'label' => 'CSS Class',
			'name' => 'class',
			'type' => 'text',
			'instructions' => 'Allows for targeted styling',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_574ebafb9e8d5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Eg. dark-box',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5710b8c3a2cf8',
			'label' => 'Image Location',
			'name' => 'image_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_574ebafb9e8d5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'None',
				'above' => 'Above Header',
				'under' => 'Under Header',
				'content' => 'Under Content',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'none',
			'layout' => 'vertical',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5710b94ba2cf9',
			'label' => 'Image Allignment',
			'name' => 'image_allignment',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_574ebafb9e8d5',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_5710b8c3a2cf8',
						'operator' => '!=',
						'value' => 'none',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_574eb93d08b57',
			'label' => 'Hook',
			'name' => 'hook',
			'type' => 'text',
			'instructions' => 'The PHP script filename<br>Eg. _hook-contact.php',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_574ebafb9e8d5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'widget',
				'operator' => '==',
				'value' => 'text_and_image_box_widget',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;