<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_57f7d72cbe251',
	'title' => 'Header Banner',
	'fields' => array (
		array (
			'key' => 'field_57f7d8a27eab2',
			'label' => 'Left Header',
			'name' => 'banner_left_header',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57f7d8c57eab3',
			'label' => 'Key Points (Left List)',
			'name' => 'key_points',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_57f7d8f87eab4',
			'min' => '',
			'max' => 6,
			'layout' => 'table',
			'button_label' => 'Add Key Point',
			'sub_fields' => array (
				array (
					'key' => 'field_57f7d8f87eab4',
					'label' => 'Key Point',
					'name' => 'key_point',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_57f7dd084412e',
			'label' => 'Key Points (Right List)',
			'name' => 'key_points_1',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_57f7d8f87eab4',
			'min' => '',
			'max' => 6,
			'layout' => 'table',
			'button_label' => 'Add Key Point',
			'sub_fields' => array (
				array (
					'key' => 'field_57f7dd084412f',
					'label' => 'Key Point',
					'name' => 'key_point',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_57f7d9ba7eab8',
			'label' => 'Banner Images',
			'name' => 'banner_images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 6,
			'insert' => 'append',
			'library' => 'all',
			'min_width' => 300,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'header-banner',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;