<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_573c64b93bd3b',
	'title' => 'Project Additional Fields',
	'fields' => array (
		array (
			'key' => 'field_573c66f172e6d',
			'label' => 'Media Content',
			'name' => 'media',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				// 'image' => 'Crop Featured Image',
				'story' => 'Story Board',
				'gallery' => 'Gallery',
				'video' => 'Video',
			),
			'default_value' => array (
				// 'image' => 'gallery',
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		// array (
		// 	'key' => 'field_573c682172e6e',
		// 	'label' => 'Letterbox Image',
		// 	'name' => 'letterbox_image',
		// 	'type' => 'image_crop',
		// 	'instructions' => 'You may crop a letterbox version of the featured image here.<br><br>However, this does not replace the featured image. That is still the most important image to set. Note that you should use the same image for both the letterbox and featured image.',
		// 	'required' => 0,
		// 	'conditional_logic' => array (
		// 		array (
		// 			array (
		// 				'field' => 'field_573c66f172e6d',
		// 				'operator' => '==',
		// 				'value' => 'image',
		// 			),
		// 		),
		// 	),
		// 	'wrapper' => array (
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'crop_type' => 'hard',
		// 	'target_size' => 'custom',
		// 	'width' => 800,
		// 	'height' => 300,
		// 	'preview_size' => 'full',
		// 	'force_crop' => 'yes',
		// 	'save_in_media_library' => 'no',
		// 	'retina_mode' => 'no',
		// 	'save_format' => 'object',
		// 	'library' => 'all',
		// ),
		array (
			'key' => 'field_573d7a12ad671',
			'label' => 'Story Board',
			'name' => 'story_board',
			'type' => 'repeater',
			'instructions' => 'Each row contains a narrative comprised of text and an image.
<br>Keep adding rows to build a story explaining the important parts of this project.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_573c66f172e6d',
						'operator' => '==',
						'value' => 'story',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_573d7a51ad672',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Story Row',
			'sub_fields' => array (
				array (
					'key' => 'field_573d81791d2b7',
					'label' => 'Subheader',
					'name' => 'subheader',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_573d7a51ad672',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
				array (
					'key' => 'field_573d7aacad673',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image_crop',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'crop_type' => 'hard',
					'target_size' => 'custom',
					'width' => 350,
					'height' => 250,
					'preview_size' => 'full',
					'force_crop' => 'yes',
					'save_in_media_library' => 'no',
					'retina_mode' => 'no',
					'save_format' => 'object',
					'library' => 'all',
				),
			),
		),
		array (
			'key' => 'field_573c68dc72e6f',
			'label' => 'Gallery',
			'name' => 'gallery',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_573c66f172e6d',
						'operator' => '==',
						'value' => 'gallery',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_573c691a72e70',
			'label' => 'Video',
			'name' => 'video',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_573c66f172e6d',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;