<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5666f0cb4d504',
	'title' => 'Form Builder',
	'fields' => array (
		array (
			'key' => 'field_56f3f13156ee1',
			'label' => 'Form Header',
			'name' => 'form_header',
			'type' => 'text',
			'instructions' => 'Header that appears over the form on the front end',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Use the form below to ask us a question',
			'placeholder' => 'Use the form below to ask us a question',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5695232e13e86',
			'label' => 'To Email',
			'name' => 'debug_email',
			'type' => 'email',
			'instructions' => 'Leave blank to send email to the default admin email.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5695245e13e87',
			'label' => 'Response Subject',
			'name' => 'response_subject',
			'type' => 'text',
			'instructions' => 'Email subject for the office',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'New Customer Enquiry',
			'placeholder' => 'New Customer Enquiry',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5695273813e8b',
			'label' => 'Response Message',
			'name' => 'response_message',
			'type' => 'wysiwyg',
			'instructions' => 'Email message for the office (appears above user enquiry)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<h3>For the attention of BrightLight Admin</h3>

A website user has made the following enquiry:',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_56f3f15656ee2',
			'label' => 'Confirmation Header',
			'name' => 'browser_output_headder',
			'type' => 'text',
			'instructions' => 'The heading in confirmation panel after a the form has been submitted',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Hold Tight, We\'ll Get Back To You',
			'placeholder' => 'Hold Tight, We\'ll Get Back To You',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5695253913e88',
			'label' => 'Auto Response Subject',
			'name' => 'auto_response_subject',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'BrightLight Auto-response (no-reply)',
			'placeholder' => 'Auto-response (no-reply)',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5695259613e89',
			'label' => 'Auto Response Message',
			'name' => 'auto_response_message',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Thank you very much for your enquiry. A BrightLight representative will be contacting you shortly.

Kind regards,
The BrightLight team.',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_56dd49e9cba91',
			'label' => 'Form Inputs',
			'name' => 'form_inputs',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56dd4a04cba92',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Input',
			'sub_fields' => array (
				array (
					'key' => 'field_56dd4a04cba92',
					'label' => 'Name',
					'name' => 'name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56dd4a10cba93',
					'label' => 'Type',
					'name' => 'type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'text' => 'Text (Default)',
						'email' => 'Email',
						'number' => 'Number',
						'url' => 'URL',
						'textarea' => 'Text Area (Multi-line Text)',
						'select' => 'Select',
						'multi_select' => 'Multiple Select',
						'file' => 'File Upload',
					),
					'default_value' => array (
						'text' => 'text',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_56dd4a6dcba94',
					'label' => 'Required',
					'name' => 'required',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Force input from user',
					'default_value' => 1,
				),
				array (
					'key' => 'field_56dd4abccba95',
					'label' => 'Placeholder',
					'name' => 'placeholder',
					'type' => 'text',
					'instructions' => 'Specifies a short hint for input',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '!=',
								'value' => 'file',
							),
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '!=',
								'value' => 'select',
							),
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '!=',
								'value' => 'multi_select',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56dd4afccba96',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => 'If different from name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56deb2e629995',
					'label' => 'Select Options',
					'name' => 'select_options',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '==',
								'value' => 'select',
							),
							array (
								'field' => 'field_56deb618e7b43',
								'operator' => '==',
								'value' => 'user',
							),
						),
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '==',
								'value' => 'multi_select',
							),
							array (
								'field' => 'field_56deb618e7b43',
								'operator' => '==',
								'value' => 'user',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_56deb33829996',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Option',
					'sub_fields' => array (
						array (
							'key' => 'field_56deb33829996',
							'label' => 'Option',
							'name' => 'option',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56deb35829997',
							'label' => 'Option Value',
							'name' => 'option_value',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
				array (
					'key' => 'field_56deb618e7b43',
					'label' => 'Select Type',
					'name' => 'select_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '==',
								'value' => 'select',
							),
						),
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '==',
								'value' => 'multi_select',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'user' => 'Manually Input',
						'select' => 'Use Predefined Options',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'user',
					'layout' => 'vertical',
				),
				array (
					'key' => 'field_56deb798e7b44',
					'label' => 'Predefined Options',
					'name' => 'predefined_options',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '==',
								'value' => 'select',
							),
							array (
								'field' => 'field_56deb618e7b43',
								'operator' => '==',
								'value' => 'select',
							),
						),
						array (
							array (
								'field' => 'field_56dd4a10cba93',
								'operator' => '==',
								'value' => 'multi_select',
							),
							array (
								'field' => 'field_56deb618e7b43',
								'operator' => '==',
								'value' => 'select',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'countries' => 'Countries',
					),
					'default_value' => array (
						'countries' => 'countries',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_56ed1eb83a4a3',
					'label' => 'Help Message',
					'name' => 'help',
					'type' => 'text',
					'instructions' => 'If different from default',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Eg. Email is not required but must be valid',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/page-form-builder.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/page-contact.php',
			),
		),
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'sign-up-form',
			),
		),	
		
		// array (
		// 	array (
		// 		'param' => 'page_template',
		// 		'operator' => '==',
		// 		'value' => 'page-templates/page-afc-flex.php',
		// 	),
		// ),
		// array (
		// 	array (
		// 		'param' => 'post_type',
		// 		'operator' => '==',
		// 		'value' => 'utility',
		// 	),
		// ),				
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;